name: 'Build'

on:
  push:
    branches: ["main", "develop", "features/*", "bugfix/*"]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Set variables
        run: |
          if [[ "${GITHUB_REF_SLUG}" == main ]]; then
            echo "CURRENT_ENV=app" >> $GITHUB_ENV
            echo "DO_DEPLOY=true" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_SLUG}" == develop ]]; then
            echo "CURRENT_ENV=dev" >> $GITHUB_ENV
            echo "DO_DEPLOY=true" >> $GITHUB_ENV
          else
            echo "CURRENT_ENV=dev" >> $GITHUB_ENV
            echo "DO_DEPLOY=false" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8 and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn -version

      - name: Compile
        run: mvn -B compile

      - name: Docker build with jib
        if: env.DO_DEPLOY=="true"
        run: mvn -B com.google.cloud.tools:jib-maven-plugin:2.6.0:dockerBuild -Dimage=frpol9cacentral.azurecr.io/demo-azure-webapp:${{ env.GITHUB_REF_SLUG_URL }}

      - name: Docker login
        if: env.DO_DEPLOY=="true"
        run: docker login -u frpol9cacentral -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} frpol9cacentral.azurecr.io

      - name: Azure login
        if: env.DO_DEPLOY=="true"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker push
        if: env.DO_DEPLOY=="true"
        run: docker push frpol9cacentral.azurecr.io/demo-azure-webapp:${{ env.GITHUB_REF_SLUG_URL }}

      - name: Webapp restart
        if: env.DO_DEPLOY
        uses: azure/CLI@v1
        with:
          azcliversion: 2.15.1
          inlineScript: az webapp restart --name frpol9-demo-azure-webapp-${{ env.CURRENT_ENV }}-app --resource-group frpol9-demo-azure-webapp-${{ env.CURRENT_ENV }}-rg
