name: 'Build'

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8 and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn -version

      - name: Compile
        run: mvn -B compile

      - name: Docker build with jib
        run: mvn -B com.google.cloud.tools:jib-maven-plugin:2.6.0:dockerBuild -Dimage=frpol9cacentral.azurecr.io/demo-azure-webapp:latest

      - name: Docker login
        run: docker login -u frpol9cacentral -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} frpol9cacentral.azurecr.io

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker push
        run: docker push frpol9cacentral.azurecr.io/demo-azure-webapp:latest

      - name: Webapp restart
        uses: azure/CLI@v1
        with:
          azcliversion: 2.15.1
          inlineScript: az webapp restart --name frpol9-demo-azure-webapp-dev-app --resource-group frpol9-demo-azure-webapp-dev-rg

      # - name: Pulumi up
      #   uses: ./.github/actions/pulumi-up
      #   with:
      #     pulumi-azure-storage-account: ${{ secrets.PULUMI_AZURE_STORAGE_ACCOUNT }}
      #     pulumi-azure-storage-key: ${{ secrets.PULUMI_AZURE_STORAGE_KEY }}
      #     pulumi-stack: ${{ env.PULUMI_STACK }}
      #     pulumi-stack-passphrase: ${{ env.PULUMI_STACK_PASSPHRASE }}
